repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        name: Flake8
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black
        name: Black
-   repo: https://github.com/prettier/prettier
    rev: 2.4.1
    hooks:
    -   id: prettier
        name: Prettier
        entry: prettier --write
        language_version: node12
        types: [javascript, json, markdown, css, less, scss, html, yaml]
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        name: isort
