name: Clang-Format

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

- name: Add LLVM repository
  run: |
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main"
    sudo apt-get update

- name: Install Clang-Format 10
  run: sudo apt-get install -y clang-format-10


      - name: Run Clang-Format
        run: |
          find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\|c\)' -exec clang-format-10 -i -style=Google {} \;
          git diff --exit-code
          
      - name: Commit formatting changes
        if: steps.clang-format.outputs.has-changes == 'yes'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Apply Clang-Format changes" -a
          git push
