name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          pip install pre-commit
          pip install isort==5.9.3
          npm install prettier

      - name: Set up pre-commit
        run: pre-commit install --install-hooks

      - name: Format with prettier
        run: npx prettier "**/*.{js,json,md,css,less,scss,html,yml}" --write

      - name: Test if prettier fixed issues
        run: |
          git diff --quiet || ( git status --short ; git diff ; exit 1 )

      - name: Format with isort
        run: isort .

      - name: Test if isort fixed issues
        run: |
          git diff --quiet || ( git status --short ; git diff ; exit 1 )

      - name: Lint with flake8
        run: flake8

      - name: Lint with black
        run: black --check .

      - name: Test if black fixed issues
        run: |
          git diff --quiet || ( git status --short ; git diff ; exit 1 )
